// Code generated by "dicon"; DO NOT EDIT.

package user

import (
	"fmt"

	"github.com/pkg/errors"
)

type dicontainer struct {
	store map[string]interface{}
}

func NewDIContainer() Container {
	return &dicontainer{
		store: map[string]interface{}{},
	}
}

func (d *dicontainer) UserService() (UserService, error) {
	if i, ok := d.store["UserService"]; ok {
		if instance, ok := i.(UserService); ok {
			return instance, nil
		}
		return nil, fmt.Errorf("invalid instance is cached %v", instance)
	}
	instance, err := NewUserService()
	if err != nil {
		return nil, errors.Wrap(err, "creation UserService failed at DICON")
	}
	d.store["UserService"] = instance
	return instance, nil
}
